version: '3'
services:
  web:
    build: './web'
    ports:
      - "4200:4200"

  api:
    build: './api'
    ports:
      - "4000:4000"

  nginx:
    image: "nginx:alpine"
    ports:
      - "8080:8080"
    volumes:
      #- ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - api
